export const ADMIN_CREATE_PRODUCT_REQUEST="ADMIN_CREATE_PRODUCT_REQUEST";
export const ADMIN_CREATE_PRODUCT_SUCCESS="ADMIN_CREATE_PRODUCT_SUCCESS";
export const ADMIN_CREATE_PRODUCT_FAIL="ADMIN_CREATE_PRODUCT_FAIL";
export const ADMIN_CREATE_PRODUCT_RESET="ADMIN_CREATE_PRODUCT_RESET";

export const ADMIN_UPDATE_PRODUCT_REQUEST="ADMIN_UPDATE_PRODUCT_REQUEST";
export const ADMIN_UPDATE_PRODUCT_SUCCESS="ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_RESET="ADMIN_UPDATE_PRODUCT_RESET";
export const ADMIN_UPDATE_PRODUCT_FAIL="ADMIN_UPDATE_PRODUCT_FAIL";

export const ADMIN_DELETE_PRODUCT_REQUEST="ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS="ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_FAIL="ADMIN_DELETE_PRODUCT_FAIL";
export const  ADMIN_DELETE_PRODUCT_RESET="ADMIN_DELETE_PRODUCT_RESET";

export const ADMIN_ALL_PRODUCT_REQUEST="ADMIN_ALL_PRODUCT_REQUEST";
export const ADMIN_ALL_PRODUCT_SUCCESS="ADMIN_ALL_PRODUCT_SUCCESS";
export const ADMIN_ALL_PRODUCT_FAIL="ADMIN_ALL_PRODUCT_FAIL";


export const ADMIN_PRODUCT_DETAILS_REQUEST="ADMIN_PRODUCT_DETAILS_REQUEST";
export const ADMIN_PRODUCT_DETAILS_SUCCESS="ADMIN_PRODUCT_DETAILS_SUCCESS";
export const ADMIN_PRODUCT_DETAILS_FAIL="ADMIN_PRODUCT_DETAILS_FAIL";

export const ADMIN_ORDERS_REQUEST="ADMIN_ORDERS_REQUEST";
export const ADMIN_ORDERS_SUCCESS="ADMIN__ORDERS_SUCCESS";
export const ADMIN_ORDERS_FAIL="ADMIN_ORDERS_FAIL";

export const ADMIN_SINGLE_ORDER_REQUEST="ADMIN_SINGLE_ORDER_REQUEST";
export const ADMIN_SINGLE_ORDER_SUCCESS="ADMIN_SINGLE_ORDER_SUCCESS";
export const ADMIN_SINGLE_ORDER_FAIL="ADMIN_SINGLE_ORDER_FAIL";


export const ADMIN_UPDATE_ORDER_REQUEST="ADMIN_UPDATE_ORDER_REQUEST";
export const ADMIN_UPDATE_ORDER_SUCCESS="ADMIN_UPDATE_ORDER_SUCCESS";
export const ADMIN_UPDATE_ORDER_FAIL="ADMIN_UPDATE_ORDER_FAIL";
export const ADMIN_UPDATE_ORDER_RESET="ADMIN_UPDATE_ORDER_RESET";


export const ADMIN_DELETE_ORDER_REQUEST="ADMIN_DELETE_ORDER_REQUEST";
export const ADMIN_DELETE_ORDER_SUCCESS="ADMIN_DELETE_ORDER_SUCCESS";
export const ADMIN_DELETE_ORDER_RESET="ADMIN_DELETE_ORDER_RESET";
export const ADMIN_DELETE_ORDER_FAIL="ADMIN_DELETE_ORDER_FAIL";


export const ADMIN_ALL_USER_REQUEST="ADMIN_ALL_USER_REQUEST";
export const ADMIN_ALL_USER_SUCCESS="ADMIN_ALL_USER_SUCCESS";
export const ADMIN_ALL_USER_FAIL="ADMIN_ALL_USER_FAIL";

export const ADMIN_SINGLE_USER_REQUEST="ADMIN_SINGLE_USER_REQUEST";
export const ADMIN_SINGLE_USER_SUCCESS="ADMIN_SINGLE_USER_SUCCESS";
export const ADMIN_SINGLE_USER_FAIL="ADMIN_SINGLE_USER_FAIL";


export const ADMIN_UPDATE_ROLE_REQUEST="ADMIN_UPDATE_ROLE_REQUEST";
export const ADMIN_UPDATE_ROLE_SUCCESS="ADMIN_UPDATE_ROLE_SUCCESS";
export const ADMIN_UPDATE_ROLE_RESET="ADMIN_UPDATE_ROLE_RESET";
export const ADMIN_UPDATE_ROLE_FAIL="ADMIN_UPDATE_ROLE_FAIL";


export const ADMIN_DELETE_USER_REQUEST="ADMIN_DELETE_USER_REQUEST";
export const ADMIN_DELETE_USER_SUCCESS="ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_RESET="ADMIN_DELETE_USER_RESET";
export const ADMIN_DELETE_USER_FAIL="ADMIN_DELETE_USER_FAIL";


export const ADMIN_PRODUCT_REVIEWS_REQUEST="ADMIN_PRODUCT_REVIEWS_REQUEST";
export const ADMIN_PRODUCT_REVIEWS_SUCCESS="ADMIN_PRODUCT_REVIEWS_SUCCESS";
export const ADMIN_PRODUCT_REVIEWS_FAIL="ADMIN_PRODUCT_REVIEWS_FAIL";

export const ADMIN_DELETE_REVIEW_REQUEST="ADMIN_DELETE_REVIEW_REQUEST";
export const ADMIN_DELETE_REVIEW_SUCCESS="ADMIN_DELETE_REVIEW_SUCCESS";
export const ADMIN_DELETE_REVIEW_RESET="ADMIN_DELETE_REVIEW_RESET";
export const ADMIN_DELETE_REVIEW_FAIL="ADMIN_DELETE_REVIEW_FAIL";








export const CLEAR_ERRORS="CLEAR_ERRORS";


