export const CREATE_ORDER_REQUEST="CREATE ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS="CREATE ORDER_REQUEST";
export const CREATE_ORDER_FAIL="CREATE ORDER_REQUEST";

export const MY_ORDER_REQUEST="MY_ORDER_REQUEST";
export const MY_ORDER_SUCCESS="MY_ORDER_SUCCES"
export const MY_ORDER_FAIL="MY_ORDER_FAIL";

export const SINGLE_ORDER_REQUEST="SINGLE_ORDER_REQUEST";
export const SINGLE_ORDER_SUCCESS="SINGLE_ORDER_SUCCESS";
export const SINGLE_ORDER_FAIL="SINGLE_ORDER_FAIL";



export const CLEAR_ERRORS="CLEAR_ERRORS";
